updated

diff --git a/bin/NextcloudBackup b/bin/NextcloudBackup
--- a/bin/NextcloudBackup
+++ b/bin/NextcloudBackup
@@ -60,6 +60,15 @@ CtrlC () {
 	exit 1
 }
 
+check_error () {
+	if [ ${1} -eq 0 ]; then
+		printf "OK\n\n"
+	else
+		printf "FAILED!\n\n"
+		p_errors=$((p_errors+1))
+	fi
+}
+
 #
 # IMPORTANT
 # You have to customize this script (directories, users, etc.) for your actual environment.
@@ -76,15 +85,16 @@ backupInternalData=false
 backupExternalData=true
 backupDatabase=true
 backupMainDir=${1:-/home/Cloud/OneDrive/ncBackup}
+remoteMainDir="OneDrive"
 currentDate=$(date +"%Y%m%d_%H%M%S")
 ExcludeTheseFiles="--exclude={\"*/files_trashbin/*\",\"*/ASA-Library-Resources/*\"}" # Be sure to add , between files
 
-# Make sure OneDrive is mounted
-echo "Checking to see if OneDrive is mounted..."
+# Make sure ${remoteMainDir} is mounted
+echo "Checking to see if ${remoteMainDir} is mounted..."
 rclonemount OD
 result=$?
 if [ $result = 0 ]; then
-	echo "OneDrive is mounted."
+	echo "${remoteMainDir} is mounted."
 else
 	backupInternalData=false
 	backupExternalData=false
@@ -94,7 +104,7 @@ fi
 
 if [ -z "$backupMainDir" ]; then
 	# TODO: The directory where you store the Nextcloud backups (when not specified by args)
-  backupMainDir='/home/Cloud/OneDrive/ncBackup'
+  backupMainDir='/home/Cloud/${remoteMainDir}/ncBackup'
 else
 	backupMainDir=$(echo $backupMainDir | sed 's:/*$::')
 fi
@@ -333,20 +343,19 @@ then
 		ls -t ${backupMainDir} | tail -$(( nrOfBackups - maxNrOfBackups )) \
 			| while read -r dirToRemove; do
 			printf "${dirToRemove}"
-			rclone purge --cache-db-purge --drive-use-trash=false OneDrive:ncBackup/${dirToRemove:?}
+			rclone purge --cache-db-purge --drive-use-trash=false ${remoteMainDir}:/$(basename $backupMainDir)/${dirToRemove:?}
 			result=$?
-			if [ ${result} -eq 0 ]; then
-				printf "OK\n\n"
-			else
-				printf "FAILED!\n\n"
-				p_errors=$((p_errors+1))
-			fi
+			check_error $result
+			printf "Removing any Trash on ${remoteMainDir}:"
+			rclone cleanup ${remoteMainDir}:
+			result=$?
+			check_error $result
 		done
 	fi
 fi
 echo
 ls -lha ${backupMainDir}/*
-sleep 60
+sleep 120
 rcloneumount OD
 echo
 echo "DONE!"
