updated

diff --git a/bin/NextcloudBackup b/bin/NextcloudBackup
--- a/bin/NextcloudBackup
+++ b/bin/NextcloudBackup
@@ -29,6 +29,15 @@ DisableMaintenanceMode () {
 	echo
 }
 
+check_error () {
+	if [ ${1} -eq 0 ]; then
+		printf "OK\n\n"
+	else
+		printf "FAILED!\n\n"
+		p_errors=$((p_errors+1))
+	fi
+}
+
 # Capture CTRL+C
 trap CtrlC INT
 
@@ -60,15 +69,6 @@ CtrlC () {
 	exit 1
 }
 
-check_error () {
-	if [ ${1} -eq 0 ]; then
-		printf "OK\n\n"
-	else
-		printf "FAILED!\n\n"
-		p_errors=$((p_errors+1))
-	fi
-}
-
 #
 # IMPORTANT
 # You have to customize this script (directories, users, etc.) for your actual environment.
@@ -77,6 +77,12 @@ check_error () {
 # ************************************************
 # Variables
 # ************************************************
+# TODO: Use compression for Matrix Synapse installation/lib dir
+# When this is the only script for backups, it's recommend to enable compression.
+# If the output of this script is used in another (compressing) backup (e.g. borg backup), 
+# you should probably disable compression here and only enable compression of your main backup script.
+useCompression=true
+
 # TODO: Set these variables to control the backup
 MaintenanceModeOn=false
 disableWebServer=false
@@ -84,27 +90,31 @@ backupFileDir=true
 backupInternalData=false
 backupExternalData=true
 backupDatabase=true
-backupMainDir=${1:-/home/Cloud/OneDrive/ncBackup}
-remoteMainDir="OneDrive"
+remoteDrive="OneDrive"
 currentDate=$(date +"%Y%m%d_%H%M%S")
 ExcludeTheseFiles="--exclude={\"*/files_trashbin/*\",\"*/ASA-Library-Resources/*\"}" # Be sure to add , between files
+# TODO: Ignore updater's backup directory in the data directory to save space
+# Set to true to ignore the backup directory
+ignoreUpdaterBackups=true
 
-# Make sure ${remoteMainDir} is mounted
-echo "Checking to see if ${remoteMainDir} is mounted..."
-rclonemount OD
-result=$?
-if [ $result = 0 ]; then
-	echo "${remoteMainDir} is mounted."
-else
-	backupInternalData=false
-	backupExternalData=false
-	backupFileDir=false
-	backupDatabase=false
-fi
+# Make sure ${remoteDrive} is mounted
+#echo "Checking to see if ${remoteDrive} is mounted..."
+#rclonemount OD
+#result=$?
+#if [ $result = 0 ]; then
+#	echo "${remoteDrive} is mounted."
+#else
+#	backupInternalData=false
+#	backupExternalData=false
+#	backupFileDir=false
+#	backupDatabase=false
+#fi
+
+backupMainDir=${1:-ncBackup}
 
 if [ -z "$backupMainDir" ]; then
 	# TODO: The directory where you store the Nextcloud backups (when not specified by args)
-  backupMainDir='/home/Cloud/${remoteMainDir}/ncBackup'
+  backupMainDir='home/Cloud/${remoteDrive}/ncBackup'
 else
 	backupMainDir=$(echo $backupMainDir | sed 's:/*$::')
 fi
@@ -112,22 +122,16 @@ fi
 # The actual directory of the current backup - this is a subdirectory of the main directory above with a timestamp
 backupdir="${backupMainDir}/${currentDate}/"
 
-# TODO: Use compression for Matrix Synapse installation/lib dir
-# When this is the only script for backups, it's recommend to enable compression.
-# If the output of this script is used in another (compressing) backup (e.g. borg backup), 
-# you should probably disable compression here and only enable compression of your main backup script.
-useCompression=true
-
 # TODO: The directory of your Nextcloud installation (this is a directory under your web root)
-nextcloudFileDir='/home/y4x/public_html/nextcloud'
+nextcloudFileDir='home/y4x/public_html/nextcloud'
 
 # TODO: The directory of your Nextcloud data directory (outside the Nextcloud file directory)
 # If your data directory is located under Nextcloud's file directory (somewhere in the web root), the data directory should not be a separate part of the backup
-nextcloudDataDir='/home/y4x/public_html/nextcloud/data'
+nextcloudDataDir='home/y4x/public_html/nextcloud/data'
 
 # TODO: The directory of your Nextcloud's local external storage.
 # Uncomment if you use local external storage.
-nextcloudLocalExternalDataDir='/var/nc_data'
+nextcloudLocalExternalDataDir='var/nc_data'
 
 # TODO: The service name of the web server. Used to start/stop web server (e.g. 'systemctl start <webserverServiceName>')
 #webserverServiceName='nginx'
@@ -150,10 +154,6 @@ dbPassword='bokstari46'
 
 # TODO: The maximum number of backups to keep (when set to 0, all backups are kept)
 maxNrOfBackups=2
-
-# TODO: Ignore updater's backup directory in the data directory to save space
-# Set to true to ignore the backup directory
-ignoreUpdaterBackups=true
 
 # File names for backup files
 # If you prefer other file names, you'll also have to change the NextcloudRestore.sh script.
@@ -218,15 +218,24 @@ else
 fi
 echo
 
+cd /
+
 #
 # Backup file directory
 #
 if [ "${backupFileDir}" = true ]; then
+	echo "${ExcludeTheseFiles}"
+	echo "${nextcloudFileDir}"
+	echo "${remoteDrive}"
+	echo "${backupdir}"
+	echo "${fileNameBackupFileDir}"
 	printf "Creating backup of Nextcloud file directory..."
 	if [ "$useCompression" = true ] ; then
-		tar -cpzf "${backupdir}/${fileNameBackupFileDir}" ${ExcludeTheseFiles} -C "${nextcloudFileDir}" .
+		tar -cpzf - . ${ExcludeTheseFiles} -C "${nextcloudFileDir}" | \
+			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupFileDir}"
 	else
-		tar -cpf "${backupdir}/${fileNameBackupFileDir}" ${ExcludeTheseFiles} -C "${nextcloudFileDir}" .
+		tar -cpf - . ${ExcludeTheseFiles} -C "${nextcloudFileDir}" | \
+			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupFileDir}"
 	fi
 	echo "Done"
 	echo
@@ -244,16 +253,20 @@ if [ "${backupInternalData}" = true ]; then
 		echo "Ignoring updater backup directory"
 		printf "Creating backup of Nextcloud Internal data directory..."
 		if [ "$useCompression" = true ] ; then
-			tar -cpzf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles}  --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" .
+			tar -cpzf - . ${ExcludeTheseFiles} --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" | \
+				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		else
-			tar -cpf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles}  --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" .
+			tar -cpf - . ${ExcludeTheseFiles} --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" | \
+				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		fi
 	else
 		printf "Creating backup of Nextcloud Internal data directory..."
 		if [ "$useCompression" = true ] ; then
-			tar -cpzf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles} -C "${nextcloudDataDir}" .
+			tar -cpzf - . ${ExcludeTheseFiles} -C "${nextcloudDataDir}" | \
+				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		else
-			tar -cpf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles} -C "${nextcloudDataDir}" .
+			tar -cpf - . ${ExcludeTheseFiles} -C "${nextcloudDataDir}" | \
+				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		fi
 	fi
 	echo "Done"
@@ -268,9 +281,11 @@ fi
 if [ "${backupExternalData}" = true ]; then
 	printf "Creating backup of Nextcloud local external storage directory..."
 	if [ "$useCompression" = true ]; then
-		tar -cpzf "${backupdir}/${fileNameBackupExternalDataDir}" ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" .
+		tar -cpzf - . ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" | \
+			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupExternalDataDir}"
 	else
-		tar -cpf "${backupdir}/${fileNameBackupExternalDataDir}" ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" .
+		tar -cpf - . ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" | \
+			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupExternalDataDir}"
 	fi
 	echo "Done"
 	echo
@@ -289,10 +304,12 @@ if [ "${backupDatabase}" = true ]; then
 			errorecho "ERROR: MySQL/MariaDB not installed (command mysqldump not found)."
 			errorecho "ERROR: No backup of database possible!"
 		else
-			mysqldump --single-transaction -h localhost -u "${dbUser}" -p"${dbPassword}" "${nextcloudDatabase}" > "${backupdir}/${fileNameBackupDb}"
+			mysqldump --single-transaction -h localhost -u "${dbUser}" -p"${dbPassword}" "${nextcloudDatabase}" | \
+			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDb}"
 		fi
 		echo "Done"
 		echo
+	# Postgress has not been adjusted
 	elif [ "${databaseSystem}" = "postgresql" ] || [ "${databaseSystem}" = "pgsql" ]; then
 		printf "Backup Nextcloud database (PostgreSQL)..."
 		if ! [ -x "$(command -v pg_dump)" ]; then
@@ -309,7 +326,6 @@ else
 	echo
 fi
 
-#
 # Start web serv
 #
 if [ ${disableWebServer} = true ]; then
@@ -320,7 +336,6 @@ if [ ${disableWebServer} = true ]; then
 	echo
 fi
 
-#
 # Disable maintenance mode
 #
 if [ "${MaintenanceModeOn}" = true ]; then
@@ -330,33 +345,30 @@ if [ "${MaintenanceModeOn}" = true ]; then
 	echo
 fi
 
-#
 # Delete old backups
 #
 if [ ${maxNrOfBackups} != 0 ]
 then
 	nrOfBackups=$(ls -l ${backupMainDir} | grep -c ^d)
-
 	if [[ ${nrOfBackups} > ${maxNrOfBackups} ]]
 	then
 		echo "Removing (rlone) old backups..."
 		ls -t ${backupMainDir} | tail -$(( nrOfBackups - maxNrOfBackups )) \
 			| while read -r dirToRemove; do
 			printf "${dirToRemove}"
-			rclone purge --cache-db-purge --drive-use-trash=false ${remoteMainDir}:/$(basename $backupMainDir)/${dirToRemove:?}
-			result=$?
-			check_error $result
-			printf "Removing any Trash on ${remoteMainDir}:"
-			rclone cleanup ${remoteMainDir}:
+			rclone purge --cache-db-purge --drive-use-trash=false ${remoteDrive}:/${backupMainDir}/${dirToRemove:?}
 			result=$?
 			check_error $result
 		done
+		printf "Removing any Trash on ${remoteDrive}:"
+		rclone cleanup ${remoteDrive}:
+		result=$?
+		check_error $result
 	fi
 fi
 echo
-ls -lha ${backupMainDir}/*
 sleep 120
-rcloneumount OD
+rclone ls ${remoteDrive}:/${backupMainDir}
 echo
 echo "DONE!"
 echo
diff --git a/bin/NextcloudBackup0 b/bin/NextcloudBackup0
--- a/bin/NextcloudBackup0
+++ b/bin/NextcloudBackup0
@@ -29,15 +29,6 @@ DisableMaintenanceMode () {
 	echo
 }
 
-check_error () {
-	if [ ${1} -eq 0 ]; then
-		printf "OK\n\n"
-	else
-		printf "FAILED!\n\n"
-		p_errors=$((p_errors+1))
-	fi
-}
-
 # Capture CTRL+C
 trap CtrlC INT
 
@@ -69,6 +60,15 @@ CtrlC () {
 	exit 1
 }
 
+check_error () {
+	if [ ${1} -eq 0 ]; then
+		printf "OK\n\n"
+	else
+		printf "FAILED!\n\n"
+		p_errors=$((p_errors+1))
+	fi
+}
+
 #
 # IMPORTANT
 # You have to customize this script (directories, users, etc.) for your actual environment.
@@ -77,12 +77,6 @@ CtrlC () {
 # ************************************************
 # Variables
 # ************************************************
-# TODO: Use compression for Matrix Synapse installation/lib dir
-# When this is the only script for backups, it's recommend to enable compression.
-# If the output of this script is used in another (compressing) backup (e.g. borg backup), 
-# you should probably disable compression here and only enable compression of your main backup script.
-useCompression=true
-
 # TODO: Set these variables to control the backup
 MaintenanceModeOn=false
 disableWebServer=false
@@ -90,31 +84,27 @@ backupFileDir=true
 backupInternalData=false
 backupExternalData=true
 backupDatabase=true
-remoteDrive="OneDrive"
+backupMainDir=${1:-/home/Cloud/OneDrive/ncBackup}
+remoteMainDir="OneDrive"
 currentDate=$(date +"%Y%m%d_%H%M%S")
 ExcludeTheseFiles="--exclude={\"*/files_trashbin/*\",\"*/ASA-Library-Resources/*\"}" # Be sure to add , between files
-# TODO: Ignore updater's backup directory in the data directory to save space
-# Set to true to ignore the backup directory
-ignoreUpdaterBackups=true
 
-# Make sure ${remoteDrive} is mounted
-#echo "Checking to see if ${remoteDrive} is mounted..."
-#rclonemount OD
-#result=$?
-#if [ $result = 0 ]; then
-#	echo "${remoteDrive} is mounted."
-#else
-#	backupInternalData=false
-#	backupExternalData=false
-#	backupFileDir=false
-#	backupDatabase=false
-#fi
-
-backupMainDir=${1:-ncBackup}
+# Make sure ${remoteMainDir} is mounted
+echo "Checking to see if ${remoteMainDir} is mounted..."
+rclonemount OD
+result=$?
+if [ $result = 0 ]; then
+	echo "${remoteMainDir} is mounted."
+else
+	backupInternalData=false
+	backupExternalData=false
+	backupFileDir=false
+	backupDatabase=false
+fi
 
 if [ -z "$backupMainDir" ]; then
 	# TODO: The directory where you store the Nextcloud backups (when not specified by args)
-  backupMainDir='home/Cloud/${remoteDrive}/ncBackup'
+  backupMainDir='/home/Cloud/${remoteMainDir}/ncBackup'
 else
 	backupMainDir=$(echo $backupMainDir | sed 's:/*$::')
 fi
@@ -122,16 +112,22 @@ fi
 # The actual directory of the current backup - this is a subdirectory of the main directory above with a timestamp
 backupdir="${backupMainDir}/${currentDate}/"
 
+# TODO: Use compression for Matrix Synapse installation/lib dir
+# When this is the only script for backups, it's recommend to enable compression.
+# If the output of this script is used in another (compressing) backup (e.g. borg backup), 
+# you should probably disable compression here and only enable compression of your main backup script.
+useCompression=true
+
 # TODO: The directory of your Nextcloud installation (this is a directory under your web root)
-nextcloudFileDir='home/y4x/public_html/nextcloud'
+nextcloudFileDir='/home/y4x/public_html/nextcloud'
 
 # TODO: The directory of your Nextcloud data directory (outside the Nextcloud file directory)
 # If your data directory is located under Nextcloud's file directory (somewhere in the web root), the data directory should not be a separate part of the backup
-nextcloudDataDir='home/y4x/public_html/nextcloud/data'
+nextcloudDataDir='/home/y4x/public_html/nextcloud/data'
 
 # TODO: The directory of your Nextcloud's local external storage.
 # Uncomment if you use local external storage.
-nextcloudLocalExternalDataDir='var/nc_data'
+nextcloudLocalExternalDataDir='/var/nc_data'
 
 # TODO: The service name of the web server. Used to start/stop web server (e.g. 'systemctl start <webserverServiceName>')
 #webserverServiceName='nginx'
@@ -154,6 +150,10 @@ dbPassword='bokstari46'
 
 # TODO: The maximum number of backups to keep (when set to 0, all backups are kept)
 maxNrOfBackups=2
+
+# TODO: Ignore updater's backup directory in the data directory to save space
+# Set to true to ignore the backup directory
+ignoreUpdaterBackups=true
 
 # File names for backup files
 # If you prefer other file names, you'll also have to change the NextcloudRestore.sh script.
@@ -218,24 +218,15 @@ else
 fi
 echo
 
-cd /
-
 #
 # Backup file directory
 #
 if [ "${backupFileDir}" = true ]; then
-	echo "${ExcludeTheseFiles}"
-	echo "${nextcloudFileDir}"
-	echo "${remoteDrive}"
-	echo "${backupDir}"
-	echo "${fileNameBackupFileDir}"
 	printf "Creating backup of Nextcloud file directory..."
 	if [ "$useCompression" = true ] ; then
-		tar -cpzf - "${nextcloudFileDir}" ${ExcludeTheseFiles} | \
-			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupFileDir}"
+		tar -cpzf "${backupdir}/${fileNameBackupFileDir}" ${ExcludeTheseFiles} -C "${nextcloudFileDir}" .
 	else
-		tar -cpf - "${nextcloudFileDir}" ${ExcludeTheseFiles} | \
-			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupFileDir}"
+		tar -cpf "${backupdir}/${fileNameBackupFileDir}" ${ExcludeTheseFiles} -C "${nextcloudFileDir}" .
 	fi
 	echo "Done"
 	echo
@@ -253,20 +244,16 @@ if [ "${backupInternalData}" = true ]; then
 		echo "Ignoring updater backup directory"
 		printf "Creating backup of Nextcloud Internal data directory..."
 		if [ "$useCompression" = true ] ; then
-			tar -cpzf - "${nextcloudDataDir}" ${ExcludeTheseFiles} --exclude="updater-*/backups/*" | \
-				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
+			tar -cpzf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles}  --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" .
 		else
-			tar -cpf - "${nextcloudDataDir}" ${ExcludeTheseFiles} --exclude="updater-*/backups/*" | \
-				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
+			tar -cpf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles}  --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" .
 		fi
 	else
 		printf "Creating backup of Nextcloud Internal data directory..."
 		if [ "$useCompression" = true ] ; then
-			tar -cpzf - "${nextcloudDataDir}" ${ExcludeTheseFiles} | \
-				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
+			tar -cpzf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles} -C "${nextcloudDataDir}" .
 		else
-			tar -cpf - "${nextcloudDataDir}" ${ExcludeTheseFiles} | \
-				rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
+			tar -cpf "${backupdir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles} -C "${nextcloudDataDir}" .
 		fi
 	fi
 	echo "Done"
@@ -281,11 +268,9 @@ fi
 if [ "${backupExternalData}" = true ]; then
 	printf "Creating backup of Nextcloud local external storage directory..."
 	if [ "$useCompression" = true ]; then
-		tar -cpzf - "${nextcloudLocalExternalDataDir}" ${ExcludeTheseFiles} | \
-			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupExternalDataDir}"
+		tar -cpzf "${backupdir}/${fileNameBackupExternalDataDir}" ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" .
 	else
-		tar -cpf - "${nextcloudLocalExternalDataDir}" ${ExcludeTheseFiles} | \
-			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupExternalDataDir}"
+		tar -cpf "${backupdir}/${fileNameBackupExternalDataDir}" ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" .
 	fi
 	echo "Done"
 	echo
@@ -304,12 +289,10 @@ if [ "${backupDatabase}" = true ]; then
 			errorecho "ERROR: MySQL/MariaDB not installed (command mysqldump not found)."
 			errorecho "ERROR: No backup of database possible!"
 		else
-			mysqldump --single-transaction -h localhost -u "${dbUser}" -p"${dbPassword}" "${nextcloudDatabase}" | \
-			rclone rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDb}"
+			mysqldump --single-transaction -h localhost -u "${dbUser}" -p"${dbPassword}" "${nextcloudDatabase}" > "${backupdir}/${fileNameBackupDb}"
 		fi
 		echo "Done"
 		echo
-	# Postgress has not been adjusted
 	elif [ "${databaseSystem}" = "postgresql" ] || [ "${databaseSystem}" = "pgsql" ]; then
 		printf "Backup Nextcloud database (PostgreSQL)..."
 		if ! [ -x "$(command -v pg_dump)" ]; then
@@ -360,11 +343,11 @@ then
 		ls -t ${backupMainDir} | tail -$(( nrOfBackups - maxNrOfBackups )) \
 			| while read -r dirToRemove; do
 			printf "${dirToRemove}"
-			rclone purge --cache-db-purge --drive-use-trash=false ${remoteDrive}:/${backupMainDir}/${dirToRemove:?}
+			rclone purge --cache-db-purge --drive-use-trash=false ${remoteMainDir}:/$(basename $backupMainDir)/${dirToRemove:?}
 			result=$?
 			check_error $result
-			printf "Removing any Trash on ${remoteDrive}:"
-			rclone cleanup ${remoteDrive}:
+			printf "Removing any Trash on ${remoteMainDir}:"
+			rclone cleanup ${remoteMainDir}:
 			result=$?
 			check_error $result
 		done
@@ -372,8 +355,8 @@ then
 fi
 echo
 ls -lha ${backupMainDir}/*
-#sleep 120
-#rcloneumount OD
+sleep 120
+rcloneumount OD
 echo
 echo "DONE!"
 echo
