updated

diff --git a/bin/NextcloudBackup2 b/bin/NextcloudBackup2
--- a/bin/NextcloudBackup2
+++ b/bin/NextcloudBackup2
@@ -29,6 +29,15 @@ DisableMaintenanceMode () {
 	echo
 }
 
+check_error () {
+	if [ ${1} -eq 0 ]; then
+		printf "OK\n\n"
+	else
+		printf "FAILED!\n\n"
+		p_errors=$((p_errors+1))
+	fi
+}
+
 # Capture CTRL+C
 trap CtrlC INT
 
@@ -68,6 +77,12 @@ CtrlC () {
 # ************************************************
 # Variables
 # ************************************************
+# TODO: Use compression for Matrix Synapse installation/lib dir
+# When this is the only script for backups, it's recommend to enable compression.
+# If the output of this script is used in another (compressing) backup (e.g. borg backup), 
+# you should probably disable compression here and only enable compression of your main backup script.
+useCompression=true
+
 # TODO: Set these variables to control the backup
 MaintenanceModeOn=false
 disableWebServer=false
@@ -75,38 +90,48 @@ backupFileDir=true
 backupInternalData=false
 backupExternalData=true
 backupDatabase=true
-backupMainDir=${1:-/home/y4x/public_html/ncBackup}
-remoteDrive="OneDrive:/ncBackup"
+remoteDrive="OneDrive"
 currentDate=$(date +"%Y%m%d_%H%M%S")
-ExcludeTheseFiles="--exclude=\"*/files_trashbin/*\"" # Be sure to add , between files
+ExcludeTheseFiles="--exclude={\"*/files_trashbin/*\",\"*/ASA-Library-Resources/*\"}" # Be sure to add , between files
+# TODO: Ignore updater's backup directory in the data directory to save space
+# Set to true to ignore the backup directory
+ignoreUpdaterBackups=true
+
+# Make sure ${remoteDrive} is mounted
+#echo "Checking to see if ${remoteDrive} is mounted..."
+#rclonemount OD
+#result=$?
+#if [ $result = 0 ]; then
+#	echo "${remoteDrive} is mounted."
+#else
+#	backupInternalData=false
+#	backupExternalData=false
+#	backupFileDir=false
+#	backupDatabase=false
+#fi
+
+backupMainDir=${1:-ncBackup}
 
 if [ -z "$backupMainDir" ]; then
 	# TODO: The directory where you store the Nextcloud backups (when not specified by args)
-  backupMainDir='/home/y4x/public_html/ncBackup'
+  backupMainDir='home/Cloud/${remoteDrive}/ncBackup'
 else
 	backupMainDir=$(echo $backupMainDir | sed 's:/*$::')
 fi
 
 # The actual directory of the current backup - this is a subdirectory of the main directory above with a timestamp
 backupDir="${backupMainDir}/${currentDate}/"
-remoteDir="${remoteDrive}/${currentDate}/"
-
-# TODO: Use compression for Matrix Synapse installation/lib dir
-# When this is the only script for backups, it's recommend to enable compression.
-# If the output of this script is used in another (compressing) backup (e.g. borg backup), 
-# you should probably disable compression here and only enable compression of your main backup script.
-useCompression=true
 
 # TODO: The directory of your Nextcloud installation (this is a directory under your web root)
-nextcloudFileDir='/home/y4x/public_html/nextcloud'
+nextcloudFileDir='home/y4x/public_html/nextcloud'
 
 # TODO: The directory of your Nextcloud data directory (outside the Nextcloud file directory)
 # If your data directory is located under Nextcloud's file directory (somewhere in the web root), the data directory should not be a separate part of the backup
-nextcloudDataDir='/home/y4x/public_html/nextcloud/data'
+nextcloudDataDir='home/y4x/public_html/nextcloud/data'
 
 # TODO: The directory of your Nextcloud's local external storage.
 # Uncomment if you use local external storage.
-nextcloudLocalExternalDataDir='/var/nc_data'
+nextcloudLocalExternalDataDir='var/nc_data'
 
 # TODO: The service name of the web server. Used to start/stop web server (e.g. 'systemctl start <webserverServiceName>')
 #webserverServiceName='nginx'
@@ -128,11 +153,7 @@ dbUser='y4x_nc_user'
 dbPassword='bokstari46'
 
 # TODO: The maximum number of backups to keep (when set to 0, all backups are kept)
-maxNrOfBackups=3
-
-# TODO: Ignore updater's backup directory in the data directory to save space
-# Set to true to ignore the backup directory
-ignoreUpdaterBackups=true
+maxNrOfBackups=2
 
 # File names for backup files
 # If you prefer other file names, you'll also have to change the NextcloudRestore.sh script.
@@ -156,7 +177,7 @@ fileNameBackupDb='nextcloud-db.sql'
 #
 # Print information
 #
-echo "Backup directory: ${backupMainDir}"
+echo "Backup directory: ${remoteDir}:/${backupMainDir}"
 
 #
 # Check for root
@@ -197,15 +218,24 @@ else
 fi
 echo
 
+cd /
+
 #
 # Backup file directory
 #
 if [ "${backupFileDir}" = true ]; then
+#	echo "${ExcludeTheseFiles}"
+#	echo "${nextcloudFileDir}"
+#	echo "${remoteDrive}"
+#	echo "${backupDir}"
+#	echo "${fileNameBackupFileDir}"
 	printf "Creating backup of Nextcloud file directory..."
 	if [ "$useCompression" = true ] ; then
-		tar -cpzf "${backupDir}/${fileNameBackupFileDir}" ${ExcludeTheseFiles} -C "${nextcloudFileDir}" .
+		tar -cpzf - ${ExcludeTheseFiles} -C "${nextcloudFileDir}" . | \
+			rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupFileDir}"
 	else
-		tar -cpf "${backupDir}/${fileNameBackupFileDir}" ${ExcludeTheseFiles} -C "${nextcloudFileDir}" .
+		tar -cpf - ${ExcludeTheseFiles} -C "${nextcloudFileDir}" . | \
+			rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupFileDir}"
 	fi
 	echo "Done"
 	echo
@@ -213,7 +243,7 @@ else
 	echo "Skipping backup of Nextcloud file directory..."
 	echo
 fi
-#exit 1
+
 #
 # Backup data directory
 #
@@ -223,22 +253,26 @@ if [ "${backupInternalData}" = true ]; then
 		echo "Ignoring updater backup directory"
 		printf "Creating backup of Nextcloud Internal data directory..."
 		if [ "$useCompression" = true ] ; then
-			tar -cpzf "${backupDir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles}  --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" .
+			tar -cpzf - ${ExcludeTheseFiles} --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" . | \
+				rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		else
-			tar -cpf "${backupDir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles}  --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" .
+			tar -cpf - ${ExcludeTheseFiles} --exclude="updater-*/backups/*" -C "${nextcloudDataDir}" . | \
+				rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		fi
 	else
 		printf "Creating backup of Nextcloud Internal data directory..."
 		if [ "$useCompression" = true ] ; then
-			tar -cpzf "${backupDir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles} -C "${nextcloudDataDir}" .
+			tar -cpzf - ${ExcludeTheseFiles} -C "${nextcloudDataDir}" . | \
+				rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		else
-			tar -cpf "${backupDir}/${fileNameBackupDataDir}" ${ExcludeTheseFiles} -C "${nextcloudDataDir}" .
+			tar -cpf - ${ExcludeTheseFiles} -C "${nextcloudDataDir}" . | \
+				rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDataDir}"
 		fi
 	fi
 	echo "Done"
 	echo
 else
-	echo "Skipping Internal Data Backup..."
+	echo "Skipping Internal Data Backup.."
 	echo
 fi
 
@@ -247,14 +281,16 @@ fi
 if [ "${backupExternalData}" = true ]; then
 	printf "Creating backup of Nextcloud local external storage directory..."
 	if [ "$useCompression" = true ]; then
-		tar -cpzf "${backupDir}/${fileNameBackupExternalDataDir}" ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" .
+		tar -cpzf - ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" . | \
+			rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupExternalDataDir}"
 	else
-		tar -cpf "${backupDir}/${fileNameBackupExternalDataDir}" ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" .
+		tar -cpf - ${ExcludeTheseFiles} -C "${nextcloudLocalExternalDataDir}" . | \
+			rclone --cache-chunk-path "${HOME}/temp" --cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupExternalDataDir}"
 	fi
 	echo "Done"
 	echo
 else
-	echo "Skipping External Data Backup..."
+	echo "Skipping External Data Backup.."
 	echo
 fi
 
@@ -268,10 +304,12 @@ if [ "${backupDatabase}" = true ]; then
 			errorecho "ERROR: MySQL/MariaDB not installed (command mysqldump not found)."
 			errorecho "ERROR: No backup of database possible!"
 		else
-			mysqldump --single-transaction -h localhost -u "${dbUser}" -p"${dbPassword}" "${nextcloudDatabase}" > "${backupDir}/${fileNameBackupDb}"
+			mysqldump --single-transaction -h localhost -u "${dbUser}" -p "${dbPassword}" "${nextcloudDatabase}" | \
+			rclone ---cache-chunk-path "${HOME}/temp" -cache-dir "${HOME}/temp" rcat "${remoteDrive}:/${backupDir}/${fileNameBackupDb}"
 		fi
 		echo "Done"
 		echo
+	# Postgress has not been adjusted
 	elif [ "${databaseSystem}" = "postgresql" ] || [ "${databaseSystem}" = "pgsql" ]; then
 		printf "Backup Nextcloud database (PostgreSQL)..."
 		if ! [ -x "$(command -v pg_dump)" ]; then
@@ -288,15 +326,6 @@ else
 	echo
 fi
 
-#
-# Move backup to remote dirve
-#
-printf  "Moving ${backupDir} contents to ${remoteDir}:"
-rclone moveto "${backupDir}" "${remoteDir}"
-echo "Done"
-echo
-
-#
 # Start web serv
 #
 if [ ${disableWebServer} = true ]; then
@@ -307,7 +336,6 @@ if [ ${disableWebServer} = true ]; then
 	echo
 fi
 
-#
 # Disable maintenance mode
 #
 if [ "${MaintenanceModeOn}" = true ]; then
@@ -317,31 +345,34 @@ if [ "${MaintenanceModeOn}" = true ]; then
 	echo
 fi
 
-#
 # Delete old backups
 #
 if [ ${maxNrOfBackups} != 0 ]
 then
-	nrOfBackups=$(ls -l ${remoteDrive} | grep -c ^d)
-
+	nrOfBackups=$(ls -l ${backupMainDir} | grep -c ^d)
 	if [[ ${nrOfBackups} > ${maxNrOfBackups} ]]
 	then
-		echo "Removing old backups..."
-		ls -t ${remoteDrive} | tail -$(( nrOfBackups - maxNrOfBackups )) \
+		echo "Removing (rlone) old backups..."
+		ls -t ${backupMainDir} | tail -$(( nrOfBackups - maxNrOfBackups )) \
 			| while read -r dirToRemove; do
-			echo "${remoteDrive}/${dirToRemove}"
-			rclone purge "${remoteDrive}/${dirToRemove}"
-#			rm -r "${remoteDrive}/${dirToRemove:?}"
+			printf "${dirToRemove}"
+			rclone purge --cache-db-purge --drive-use-trash=false ${remoteDrive}:/${backupMainDir}/${dirToRemove:?}
+			result=$?
+			check_error $result
 		done
+		printf "Removing any Trash on ${remoteDrive}:"
+		rclone cleanup ${remoteDrive}:
+		result=$?
+		check_error $result
 	fi
 fi
 echo
-rclone lsf ${remoteDrive}
-#ls -la ${remoteDrive}
+sleep 120
+rclone ls ${remoteDrive}:/${backupMainDir}
 echo
 echo "DONE!"
 echo
-echo "Backup ${remoteDir} created:"
+echo "Backup created: ${backupDir}"
 echo
 duration=${SECONDS}
 echo -e "\n**Nextcloud Backup completed in $(show_time ${duration})"
