updated

diff --git a/bin/roottarbal b/bin/roottarbal
--- a/bin/roottarbal
+++ b/bin/roottarbal
@@ -4,21 +4,32 @@ cd /cpbackup/
 FileDate="${1:-$(date +%F)}"
 FileName="root-dir-${FileDate}"
 
+check_error () {
+	local result=${1}
+	if [ ${result} -eq 0 ]; then
+		printf "OK\n\n"
+	else
+		printf "FAILED!\n\n"
+		r_errors=$((r_errors+1))
+	fi
+}
+
 # Work starts here
 r_errors=0
 # Backup /root directory
 printf "\n** Making /root tarball (/cpbackup/${FileDate}/root-dir.tgz)..."
 tar -czf /cpbackup/${FileDate}/root-dir.tgz -X ${HOME}/root-Exclude /root 2> ~/roottarbal.err
 result=$?
-if [ ${result} -eq 0 ]; then
-	printf "OK\n\n"
-else
-	printf "FAILED!\n\n"
-	r_errors=$((r_errors+1))
-fi
+check_error ${result}
 ls -la /cpbackup/${FileDate}/root-dir.tgz
+# Backup /home/elton directory
+printf "\n** Making /home/elton tarball (/cpbackup/${FileDate}/elton-dir.tgz)..."
+tar -czf /cpbackup/${FileDate}/elton-dir.tgz -X ${HOME}/elton-Exclude /home/elton 2>> ~/roottarbal.err
+result=$?
+check_error ${result}
+ls -la /cpbackup/${FileDate}/elton-dir.tgz
 # Show number of t_errors during Backup transfer.
-echo -e "\n/root tarbal completed with ${r_errors} errors.\n"
+echo -e "\nTarbals completed with ${r_errors} errors.\n"
 # Show time to do the transfer
 duration=${SECONDS}
 echo -e "\n** /root tarbal completed in $(show_time ${duration})\n"
